spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: "jdbc:postgresql://localhost:5432/bd_transacao"
    username: postgres
    password: postgres

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: "true"
    database-platform: "org.hibernate.dialect.PostgreSQL94Dialect"
server:
  port: 16029


# Ativar o modo de depuração do Spring Boot
  debug: true
